export enum ApplicationModal {
  SHARE,
  CREATE_IDEA_MODAL,
  QR_CODE_MODAL,
  ADD_QUESTION_MODAL,
  DISLIKE_MODAL,
  WALLET_ADDRESS_MODAL,
  PREFERENCE_MODAL,
  CREATE_AGENT_MODAL,
  DELETE_MY_AGENT_MODAL,
  ACCOUNT_MANEGE_MODAL,
  EDIT_NICKNAME_MODAL,
  EDIT_AVATAR_MODAL,
  BIND_WALLET_MODAL,
  DEPOSIT_AND_WITHDRAW_MODAL,
  CONNECT_WALLET_MODAL,
  SWITCH_CHAIN_MODAL,
  EDIT_STRATEGY_INFO_MODAL,
  DEPLOY_MODAL,
  PROMPT_MODAL,
  DELIST_STRATEGY_MODAL,
  PAUSE_STRATEGY_MODAL,
  DELETE_STRATEGY_MODAL,
  SHARE_STRATEGY_MODAL,
}

export interface ImgListType {
  key: string
  id: string
  customerItem: ReactNode
}

export enum MOBILE_TABS_TYPE {
  BORDER,
  COMMON,
}

type ID = number
type NAME = string
type SYMBOL = string
export type CoinIdData = [ID, NAME, SYMBOL]
