/**
 * 时区配置
 */

import dayjs from 'dayjs'
export const SUPPORTED_TIMEZONES = [
  'Etc/UTC',
  'Pacific/Honolulu',
  'America/Juneau',
  'America/Vancouver',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/El_Salvador',
  'America/Chicago',
  'America/Mexico_City',
  'America/Bogota',
  'America/Lima',
  'America/Caracas',
  'America/New_York',
  'America/Santiago',
  'America/Toronto',
  'America/Argentina/Buenos_Aires',
  'America/Sao_Paulo',
  'Atlantic/Reykjavik',
  'Africa/Lagos',
  'Europe/London',
  'Europe/Belgrade',
  'Europe/Berlin',
  'Africa/Cairo',
  'Europe/Copenhagen',
  'Africa/Johannesburg',
  'Europe/Luxembourg',
  'Europe/Madrid',
  'Europe/Oslo',
  'Europe/Paris',
  'Europe/Rome',
  'Europe/Stockholm',
  'Europe/Warsaw',
  'Europe/Zurich',
  'Europe/Athens',
  'Europe/Dublin',
  'Europe/Lisbon',
  'Europe/Amsterdam',
  'Europe/Brussels',
  'Europe/Malta',
  'Asia/Bahrain',
  'Europe/Helsinki',
  'Europe/Istanbul',
  'Asia/Jerusalem',
  'Asia/Kuwait',
  'Europe/Moscow',
  'Asia/Qatar',
  'Europe/Riga',
  'Asia/Riyadh',
  'Europe/Tallinn',
  'Europe/Vilnius',
  'Asia/Dubai',
  'Asia/Muscat',
  'Asia/Tehran',
  'Asia/Ashkhabad',
  'Asia/Kolkata',
  'Asia/Almaty',
  'Asia/Bangkok',
  'Asia/Ho_Chi_Minh',
  'Asia/Jakarta',
  'Asia/Chongqing',
  'Asia/Hong_Kong',
  'Australia/Perth',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Taipei',
  'Asia/Seoul',
  'Asia/Tokyo',
  'Australia/Adelaide',
  'Australia/Brisbane',
  'Australia/Sydney',
  'Pacific/Norfolk',
  'Pacific/Auckland',
  'Pacific/Fakaofo',
  'Pacific/Chatham',
  'US/Mountain',
]

export const TIMEZONE_LABELS_ORIGIN = {
  'Etc/UTC': 'UTC',
  'Pacific/Honolulu': '(UTC{{offset}}) Honolulu',
  'America/Juneau': '(UTC{{offset}}) Juneau',
  'America/Los_Angeles': '(UTC{{offset}}) Los Angeles',
  'America/Phoenix': '(UTC{{offset}}) Phoenix',
  'US/Mountain': '(UTC{{offset}}) Denver',
  'America/Vancouver': '(UTC{{offset}}) Vancouver',
  'America/El_Salvador': '(UTC{{offset}}) San Salvador',
  'America/Bogota': '(UTC{{offset}}) Bogota',
  'America/Chicago': '(UTC{{offset}}) Chicago',
  'America/Lima': '(UTC{{offset}}) Lima',
  'America/Mexico_City': '(UTC{{offset}}) Mexico City',
  'America/Caracas': '(UTC{{offset}}) Caracas',
  'America/New_York': '(UTC{{offset}}) New York',
  'America/Santiago': '(UTC{{offset}}) Santiago',
  'America/Toronto': '(UTC{{offset}}) Toronto',
  'America/Argentina/Buenos_Aires': '(UTC{{offset}}) Buenos Aires',
  'America/Sao_Paulo': '(UTC{{offset}}) Sao Paulo',
  'Atlantic/Reykjavik': '(UTC) Reykjavik',
  'Africa/Lagos': '(UTC{{offset}}) Lagos',
  'Europe/London': '(UTC{{offset}}) London',
  'Europe/Belgrade': '(UTC{{offset}}) Belgrade',
  'Europe/Berlin': '(UTC{{offset}}) Berlin',
  'Africa/Cairo': '(UTC{{offset}}) Cairo',
  'Europe/Copenhagen': '(UTC{{offset}}) Copenhagen',
  'Africa/Johannesburg': '(UTC{{offset}}) Johannesburg',
  'Europe/Luxembourg': '(UTC{{offset}}) Luxembourg',
  'Europe/Madrid': '(UTC{{offset}}) Madrid',
  'Europe/Oslo': '(UTC{{offset}}) Oslo',
  'Europe/Paris': '(UTC{{offset}}) Paris',
  'Europe/Rome': '(UTC{{offset}}) Rome',
  'Europe/Stockholm': '(UTC{{offset}}) Stockholm',
  'Europe/Warsaw': '(UTC{{offset}}) Warsaw',
  'Europe/Zurich': '(UTC{{offset}}) Zurich',
  'Europe/Athens': '(UTC{{offset}}) Athens',
  'Asia/Bahrain': '(UTC{{offset}}) Bahrain',
  'Europe/Helsinki': '(UTC{{offset}}) Helsinki',
  'Europe/Istanbul': '(UTC{{offset}}) Istanbul',
  'Europe/Dublin': '(UTC{{offset}}) Dublin',
  'Europe/Lisbon': '(UTC{{offset}}) Lisbon',
  'Europe/Amsterdam': '(UTC{{offset}}) Amsterdam',
  'Europe/Brussels': '(UTC{{offset}}) Brussels',
  'Europe/Malta': '(UTC{{offset}}) Malta',
  'Asia/Jerusalem': '(UTC{{offset}}) Jerusalem',
  'Asia/Kuwait': '(UTC{{offset}}) Kuwait',
  'Europe/Moscow': '(UTC{{offset}}) Moscow',
  'Asia/Qatar': '(UTC{{offset}}) Qatar',
  'Europe/Riga': '(UTC{{offset}}) Riga',
  'Asia/Riyadh': '(UTC{{offset}}) Riyadh',
  'Europe/Tallinn': '(UTC{{offset}}) Tallinn',
  'Europe/Vilnius': '(UTC{{offset}}) Vilnius',
  'Asia/Dubai': '(UTC{{offset}}) Dubai',
  'Asia/Muscat': '(UTC{{offset}}) Muscat',
  'Asia/Tehran': '(UTC{{offset}}) Tehran',
  'Asia/Ashkhabad': '(UTC{{offset}}) Ashkhabad',
  'Asia/Kolkata': '(UTC{{offset}}) Kolkata',
  'Asia/Almaty': '(UTC{{offset}}) Almaty',
  'Asia/Bangkok': '(UTC{{offset}}) Bangkok',
  'Asia/Ho_Chi_Minh': '(UTC{{offset}}) Ho Chi Minh',
  'Asia/Jakarta': '(UTC{{offset}}) Jakarta',
  'Asia/Chongqing': '(UTC{{offset}}) Chongqing',
  'Asia/Hong_Kong': '(UTC{{offset}}) Hong Kong',
  'Australia/Perth': '(UTC{{offset}}) Perth',
  'Asia/Shanghai': '(UTC{{offset}}) Shanghai',
  'Asia/Singapore': '(UTC{{offset}}) Singapore',
  'Asia/Taipei': '(UTC{{offset}}) Taipei',
  'Asia/Seoul': '(UTC{{offset}}) Seoul',
  'Asia/Tokyo': '(UTC{{offset}}) Tokyo',
  'Australia/Adelaide': '(UTC{{offset}}) Adelaide',
  'Australia/Brisbane': '(UTC{{offset}}) Brisbane',
  'Australia/Sydney': '(UTC{{offset}}) Sydney',
  'Pacific/Norfolk': '(UTC{{offset}}) Norfolk Island',
  'Pacific/Auckland': '(UTC{{offset}}) New Zealand',
  'Pacific/Chatham': '(UTC{{offset}}) Chatham Islands',
  'Pacific/Fakaofo': '(UTC{{offset}}) Tokelau',
}

export const TIMEZONE_LABELS = new Proxy(TIMEZONE_LABELS_ORIGIN, {
  get: (target, name: keyof typeof TIMEZONE_LABELS_ORIGIN) => {
    if (!(name in TIMEZONE_LABELS_ORIGIN)) return ''
    const text = target[name]
    const offset = dayjs.tz(Date.now(), name).utcOffset()
    const offsetAbs = Math.abs(offset)
    const offsetFormat = `${offset > 0 ? '+' : offset < 0 ? '-' : '' }${Math.floor(offsetAbs / 60) || ''}${offsetAbs % 60 > 0 ? `:${offsetAbs % 60}` : ''}`
    return text.replace("{{offset}}", offsetFormat)
  }
})