import { Trans } from '@lingui/react/macro'
import { IconBase } from 'components/Icons'
import Tooltip from 'components/Tooltip'
import { vm } from 'pages/helper'
import { useMemo } from 'react'
import { useIsMobile } from 'store/application/hooks'
import { BacktestDataType } from 'store/agentdetail/agentdetail'
import styled, { css, useTheme } from 'styled-components'
import { div, isLt, sub, toFix } from 'utils/calc'
import { formatPercent } from 'utils/format'

const DataListWrapper = styled.div`
  display: flex;
  justify-content: flex-start;
  width: 100%;
  gap: 4px;
  flex-wrap: wrap;
  ${({ theme }) =>
    theme.isMobile &&
    css`
      flex-direction: row;
      gap: 0;
      padding: ${vm(8)};
      border-radius: ${vm(12)};
      background-color: ${({ theme }) => theme.bgT20};
      position: relative;

      /* 中间竖线分割 */
      &::before {
        content: '';
        position: absolute;
        left: 50%;
        top: ${vm(8)};
        bottom: ${vm(8)};
        width: 1px;
        background-color: ${({ theme }) => theme.bgT20};
        transform: translateX(-50%);
      }
    `}
`

const ColumnWrapper = styled.div`
  display: none;
  ${({ theme }) =>
    theme.isMobile &&
    css`
      display: flex;
      flex-direction: column;
      width: 50%;
      gap: ${vm(8)};
      &:last-child {
        padding-left: ${vm(12)};
      }
    `}
`

const ItemWrapper = styled.div<{ $isFromUseCases?: boolean }>`
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 4px;
  width: calc((100% - 8px) / 3);
  height: 58px;
  padding: 8px 12px;
  border-radius: 12px;
  background-color: ${({ theme }) => theme.bgT20};
  .title {
    display: flex;
    align-items: center;
    gap: 4px;
    white-space: nowrap;
    font-size: 12px;
    font-weight: 400;
    line-height: 18px;
    color: ${({ theme }) => theme.textL3};
    .icon-warn {
      transform: rotate(180deg);
      font-size: 14px;
      color: ${({ theme }) => theme.textL4};
    }
  }
  .value {
    font-size: 14px;
    font-weight: 500;
    line-height: 20px;
    color: ${({ theme }) => theme.textL1};
  }
  ${({ theme }) => theme.mediaMinWidth.minWidth1024`
    width: calc((100% - 8px) / 3);
  `}
  ${({ theme }) => theme.mediaMinWidth.minWidth1280`
    width: calc((100% - 12px) / 4);
  `}
  ${({ theme }) => theme.mediaMinWidth.minWidth1680`
    width: calc((100% - 20px) / 6);
  `}
 
  ${({ theme, $isFromUseCases }) =>
    theme.isMobile
      ? css`
          gap: ${vm(4)};
          width: 100%;
          height: ${vm(42)};
          padding: 0;
          background-color: transparent;
          min-width: unset;
          .title {
            gap: ${vm(4)};
            font-size: 0.12rem;
            line-height: 0.18rem;
            .icon-warn {
              font-size: 0.14rem;
            }
          }
          .value {
            font-size: 0.14rem;
            line-height: 0.2rem;
          }
        `
      : css`
          ${$isFromUseCases &&
          css`
            width: calc((100% - 12px) / 4) !important;
          `}
        `}
`

export default function DataList({
  isFromUseCases = false,
  backtestData,
}: {
  isFromUseCases?: boolean
  backtestData: BacktestDataType
}) {
  const theme = useTheme()
  const isMobile = useIsMobile()
  const {
    final_value,
    maximum_drawdown_rates,
    sharpe_ratio,
    details,
    win_rates,
    initial_value,
    maximum_drawdown_value,
    profit_factor,
    trades_per_day,
    avg_losing_trade,
    avg_winning_trade,
    run_up,
    annualized_return_rates,
    run_up_rates,
  } = backtestData
  const pnl = sub(final_value, initial_value)
  const pnlRate = div(pnl, initial_value)
  const itemList = useMemo(() => {
    return [
      {
        key: 'initialEquity',
        title: <Trans>Initial equity</Trans>,
        value: initial_value ? toFix(initial_value, 2) : '--',
        tooltip: 'The starting capital used at the beginning of backtest or live trading.',
      },
      {
        key: 'Max drawdown',
        title: <Trans>Max drawdown</Trans>,
        value: maximum_drawdown_rates ? `${toFix(maximum_drawdown_value, 2)}(${maximum_drawdown_rates})` : '--',
        tooltip: 'The largest peak-to-trough decline in equity during the period.',
      },
      {
        key: 'Max Run-up',
        title: <Trans>Max Run-up</Trans>,
        value: run_up_rates ? `${toFix(run_up, 2)}(${run_up_rates})` : '--',
        tooltip: 'The largest increase in equity from a trough to the next peak.',
      },
      {
        key: 'PnL',
        title: <Trans>PnL</Trans>,
        value: `${Number(toFix(pnl, 2))}(${formatPercent({ value: pnlRate, precision: 2 })})`,
        tooltip: 'Total net profit or loss generated by the strategy.',
        valueStyle: isLt(pnl, 0) ? { color: theme.red100 } : { color: theme.green100 },
      },
      {
        key: 'APR (Annualized Return)',
        title: <Trans>APR</Trans>,
        value: annualized_return_rates || '--',
        tooltip: 'Annualized percentage return based on total strategy performance.',
        valueStyle:
          typeof annualized_return_rates === 'string' && (annualized_return_rates || '').includes('-')
            ? { color: theme.red100 }
            : { color: theme.green100 },
      },
      {
        key: 'Total trades',
        title: <Trans>Total trades</Trans>,
        value: details?.length || '--',
        tooltip: 'Total number of trades executed during the period.',
      },
      {
        key: 'Trades per Day',
        title: <Trans>Trades per Day</Trans>,
        value: trades_per_day || '--',
        tooltip: 'Average number of trades executed per day.',
      },
      {
        key: 'Win Rate',
        title: <Trans>Win Rate</Trans>,
        value: win_rates || '--',
        tooltip: 'The percentage of trades that were profitable.',
      },
      {
        key: 'Avg Winning Trade',
        title: <Trans>Avg Winning Trade</Trans>,
        value: avg_winning_trade || '--',
        tooltip: 'The average profit from winning trades.',
      },
      {
        key: 'Avg Losing Trade',
        title: <Trans>Avg Losing Trade</Trans>,
        value: avg_losing_trade || '--',
        tooltip: 'The average loss from losing trades.',
      },
      {
        key: 'Profit Factor',
        title: <Trans>Profit Factor</Trans>,
        value: profit_factor || '--',
        tooltip: 'Ratio of gross profits to gross losses; a measure of risk/reward efficiency.',
      },
      {
        key: 'Sharpe ratio',
        title: <Trans>Sharpe ratio</Trans>,
        value: sharpe_ratio || '--',
        tooltip: 'The excess return per unit of risk (volatility); used to evaluate risk-adjusted return.',
      },
    ]
  }, [
    win_rates,
    maximum_drawdown_rates,
    sharpe_ratio,
    details?.length,
    initial_value,
    maximum_drawdown_value,
    run_up_rates,
    profit_factor,
    trades_per_day,
    avg_losing_trade,
    avg_winning_trade,
    run_up,
    annualized_return_rates,
    pnlRate,
    pnl,
    theme.red100,
    theme.green100,
  ])

  // 移动端分左右两列
  const leftColumnItems = isMobile ? itemList.slice(0, Math.ceil(itemList.length / 2)) : []
  const rightColumnItems = isMobile ? itemList.slice(Math.ceil(itemList.length / 2)) : []

  return (
    <DataListWrapper className='data-list-wrapper'>
      {isMobile ? (
        <>
          <ColumnWrapper>
            {leftColumnItems.map((item) => {
              const { key, title, value, tooltip, valueStyle } = item
              return (
                <ItemWrapper className='item-wrapper' key={key}>
                  <span className='title'>
                    {title}
                    <Tooltip placement='top' content={tooltip}>
                      <IconBase className='icon-warn' />
                    </Tooltip>
                  </span>
                  <span style={valueStyle || {}} className='value'>
                    {value}
                  </span>
                </ItemWrapper>
              )
            })}
          </ColumnWrapper>
          <ColumnWrapper>
            {rightColumnItems.map((item) => {
              const { key, title, value, tooltip, valueStyle } = item
              return (
                <ItemWrapper className='item-wrapper' key={key}>
                  <span className='title'>
                    {title}
                    <Tooltip placement='top' content={tooltip}>
                      <IconBase className='icon-warn' />
                    </Tooltip>
                  </span>
                  <span style={valueStyle || {}} className='value'>
                    {value}
                  </span>
                </ItemWrapper>
              )
            })}
          </ColumnWrapper>
        </>
      ) : (
        itemList.map((item) => {
          const { key, title, value, tooltip, valueStyle } = item
          return (
            <ItemWrapper $isFromUseCases={isFromUseCases} className='item-wrapper' key={key}>
              <span className='title'>
                {title}
                <Tooltip placement='top' content={tooltip}>
                  <IconBase className='icon-warn' />
                </Tooltip>
              </span>
              <span style={valueStyle || {}} className='value'>
                {value}
              </span>
            </ItemWrapper>
          )
        })
      )}
    </DataListWrapper>
  )
}
