import styled from 'styled-components'
import StrategyInfo from './components/StrategyInfo'
import { Trans } from '@lingui/react/macro'
import ActionLayer from '../ActionLayer'
import { useCallback } from 'react'
import { useStrategyInfoTabIndex } from 'store/createstrategy/hooks/useTabIndex'

const SummaryWrapper = styled.div`
  display: flex;
  flex-direction: column;
  gap: 20px;
  width: 100%;
`

const CompleteContent = styled.div`
  display: flex;
  flex-direction: column;
  gap: 8px;
`

const CompleteInfo = styled.div`
  font-size: 14px;
  font-style: normal;
  font-weight: 500;
  line-height: 20px;
  color: ${({ theme }) => theme.textL3};
`

const ActionList = styled.div`
  display: flex;
  align-items: center;
  width: 100%;
  gap: 12px;
  .action-layer-wrapper {
    width: 50%;
  }
`

export default function Summary() {
  const [, setStrategyInfoTabIndex] = useStrategyInfoTabIndex()
  const goCodeTab = useCallback(() => {
    setStrategyInfoTabIndex(1)
  }, [setStrategyInfoTabIndex])
  const goBacktestTab = useCallback(() => {
    setStrategyInfoTabIndex(2)
  }, [setStrategyInfoTabIndex])
  return (
    <SummaryWrapper>
      <CompleteContent>
        <CompleteInfo>
          <Trans>Your configuration is complete. You can now run the strategy.</Trans>
        </CompleteInfo>
        <ActionList>
          <ActionLayer
            showRightArrow
            iconCls='icon-view-code'
            title={<Trans>View code</Trans>}
            description={<Trans>Generated by the Agent</Trans>}
            clickCallback={goCodeTab}
          />
          <ActionLayer
            showRightArrow
            iconCls='icon-backtest'
            title={<Trans>Verify History (Backtest)</Trans>}
            description={<Trans>See how this strategy would have performed in the past.</Trans>}
            clickCallback={goBacktestTab}
          />
        </ActionList>
      </CompleteContent>
      <StrategyInfo />
    </SummaryWrapper>
  )
}
